app/models.py
from . import db,login_manager
from datetime import datetime
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin

@login_manager.user_loader
def load_user(user_id):
  return User.query.get(int(user_id))

class User(UserMixin,db.Model):
  '''
  user class to define user objects
  '''
  __tablename__='users'

  id=db.Column(db.Integer,primary_key = True)
  username=db.Column(db.String(255),index=True)
  email=db.Column(db.String(255),unique=True,index=True)
  pass_secure=db.Column(db.String(255))
  password_hash=db.Column(db.String(255))
  bio=db.Column(db.String(255))
  profile_pic_path=db.Column(db.String())

  pitches=db.relationship('Pitch',backref='user',lazy="dynamic")
  comment=db.relationship('Comment',backref='user',lazy='dynamic')
  
  @property
  def password(self):
    raise AttributeError('You cannot read the password attribute')
  @password.setter
  def password(self,password):
    self.pass_secure=generate_password_hash(password)
  def verify_password(self,password):
    return check_password_hash(self.pass_secure,password) 
  def save_user(self):
    db.session.add(self)
    db.session.commit()  
  def get_pitches():
    user=User.query.filter_by(id=self.id).first()
    return user.pitches   
  def __repr__(self):
    return f'User {self.username}' 

class Pitch(db.Model):
  '''
  pitch class to define pitch objects
  '''
  __tablename__ ='pitches'
  id = db.Column(db.Integer, primary_key = True)
  title = db.Column(db.String(255))
  description = db.Column(db.String(700))
  category = db.Column(db.String)
  posted = db.Column(db.DateTime, default=datetime.utcnow)
  upvotes = db.Column(db.Integer)
  downvotes = db.Column(db.Integer)
  user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
  comments = db.relationship('Comment', backref = 'pitch', lazy = 'dynamic')

  def save_pitch(self):
    """
    Method that saves a pitch to the database
    """
    db.session.add(self)
    db.session.commit()

  @classmethod
  def get_pitches(cls,category):
    pitches = Pitch.query.filter_by(category=category).all()
    return pitches  

  @classmethod
  def get_pitch(cls,id):
    pitch=Pitch.query.filter_by(id=id).first()
    return pitch

  @classmethod
  def count_pitches(cls,uname):
    user = User.query.filter_by(username=uname).first()
    pitches = Pitch.query.filter_by(user_id=user.id).all()
    pitches_count = 0
    for pitch in pitches:
      pitches_count += 1
    return pitches_count
  def get_comments(self):
    """
    Method that retrieves a pitch's comments.
    """
    pitch = Pitch.query.filter_by(id = self.id).first()
    comments = Comment.query.filter_by(pitch_id = pitch.id).all()
    return comments    
class Comment(db.Model):
  '''
  comment class to define comment objects
  ''' 
  __tablename__='comments'
  id = db.Column(db.Integer,primary_key=True)
  pitch_id = db.Column(db.Integer, db.ForeignKey('pitches.id'), nullable=False)
  user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable= False)
  content = db.Column(db.String)
  
  def save_comment(self):
    db.session.add(self)
    db.session.commit()

  def __repr__(self):
    """
    Method used for debugging the database.
    """
    return f'User {self.content}'  

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField,FileField
from wtforms.validators import Required

class UpdateProfile(FlaskForm):
  bio = TextAreaField('Tell us about you.',validators = [Required()])
  submit = SubmitField('Submit')
class NewPitch(FlaskForm):
  title = StringField("Pitch Title", validators = [Required()])
  pitch = TextAreaField("Description", validators = [Required()])  
  category=SelectField("Category",
  choices=[("interview","interview"),("motivation","motivation"),("product","product"),("promotion","promotion")],validators = [Required()])
  submit=SubmitField("Add Pitch")
class CommentForm(FlaskForm):
  text = TextAreaField('Leave a comment:',validators=[Required()])
  submit=SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_simplemde import SimpleMDE
from flask_login import LoginManager
# from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
simple=SimpleMDE()
db=SQLAlchemy()
# photos = UploadSet('photos',IMAGES)
mail=Mail()

def create_app(config_name):
  # Initializing application
  app = Flask(__name__)
  # Setting up configuration
  app.config.from_object(config_options[config_name])
  # Initializing Flask Extensions
  bootstrap.init_app (app)
  simple.init_app(app)
  db.init_app(app)
  login_manager.init_app(app)
  mail.init_app(app)
  # Registering the blueprint
  from .main import main as main_blueprint
  app.register_blueprint(main_blueprint)
  #authentication blueprint
  from .auth import auth as auth_blueprint
  app.register_blueprint(auth_blueprint,url_prefix='/authenticate')
   #configure Uploadset
#   configure_uploads(app,photos)

  return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from ..models import User,Pitch,Comment
from .forms import UpdateProfile,NewPitch,CommentForm
from .. import db
from flask_login import login_required,current_user

#views
@main.route('/')
def index():
  '''view root that returns index page'''
  pitches = Pitch.query.all()
  users = User.query.all()
  return render_template('index.html',pitches = pitches, users = users)  

@main.route('/pitches/<category>')
def get_pitches_category(category):
  pitches = Pitch.get_pitches(category)
  return render_template("index.html", pitches = pitches)

@main.route('/user/<uname>')
def profile(uname):
  user = User.query.filter_by(username = uname).first()
  if user is None:
    abort(404)
  pitches=Pitch.query.filter_by(user_id=user.id).all()
  pitches_count=Pitch.count_pitches(uname)

  return render_template("profile/profile.html", user = user,pitches=pitches,pitches_count=pitches_count)
@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
  user = User.query.filter_by(username = uname).first()
  if user is None:
    abort(404)
  form = UpdateProfile()
  if form.validate_on_submit():
    user.bio = form.bio.data

    db.session.add(user)
    db.session.commit()

    return redirect(url_for('.profile',uname=user.username))

  return render_template('profile/update.html',form =form,user=user)
@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
  user = User.query.filter_by(username = uname).first()
  if 'photo' in request.files:
    filename = photos.save(request.files['photo'])
    path = f'photos/{filename}'
    user.profile_pic_path = path
    db.session.commit()
  return redirect(url_for('main.profile',uname=uname))  
@main.route('/pitch/new', methods = ['GET','POST'])
@login_required
def add_pitch():
  form = NewPitch()
  if form.validate_on_submit():
    title = form.title.data
    pitch = form.pitch.data
    category = form.category.data

    # Updated pitch instance
    new_pitch = Pitch(title=title,description=pitch,category=category, user = current_user, upvotes=0,downvotes=0)

    # Save pitch method
    new_pitch.save_pitch()
    return redirect(url_for('.index'))

  title = 'New pitch'
  return render_template('newpitch.html',title = title,pitch_form=form )  

@main.route('/pitch/<int:id>', methods = ['GET','POST'])
def pitch(id):
  pitch = Pitch.get_pitch(id)
  if request.args.get("upvote"):
    pitch.upvotes += 1
    db.session.add(pitch)
    db.session.commit()
    return redirect("/pitch/{pitch_id}".format(pitch_id=pitch.id))

  elif request.args.get("downvote"):
    pitch.downvotes += 1
    db.session.add(pitch)
    db.session.commit()
    return redirect("/pitch/{pitch_id}".format(pitch_id=pitch.id))

  comment_form = CommentForm()
  if comment_form.validate_on_submit():
    comment = comment_form.text.data

    new_comment = Comment(content = comment,user = current_user,pitch_id = pitch.id)

    new_comment.save_comment()
  comments = Pitch.get_comments(pitch)

  return render_template("pitch.html", pitch = pitch, comment_form = comment_form, comments = comments)  

app/templates/base.html
 
{% extends 'bootstrap/base.html'%}

<!-- Navbar block  --> 
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}
{%block styles %}
  {{super()}}
  <!--Importing the simple mde css and js files  -->
  {{ simplemde.css}}
  {{ simplemde.js }}

{% endblock %}

app/templates/four0wfour.html
{% extends 'base.html' %}
{% block styles%}
  {{ super() }}
  <link rel="stylesheet" href="{{url_for('static' , filename='css/index.css')}}">
{% endblock %}
{% block content %}
<div class="container">
  <h1 class="text-center text-danger">WHOOOPSSSSSSS !</h1>
  <h2 class="text-center text-danger">We cannot find the page your looking for <br>.Click the link below to head back to the homepage</h2>
  <a href="/"><h3 class="text-warning text-center">BACK TO HOMEPAGE</h3></a> 
</div>    

{% endblock %}

app/templates/index.html
{% extends 'base.html'%}
{% block styles%}
  {{ super() }}
  <link rel="stylesheet" href="{{url_for('static' , filename='css/index.css')}}">
{% endblock %}
{% block content %}
<div class="container">
  <h1 class="text-center"><u>PITCH</u></h1>
  {%if pitches%}
  <div class="row">
    {%for pitch in pitches%}
      <div class="col-md-6">
        <div class="card">
          <div class="card-body">
            <h3 class="text-capitalize"><u>{{(pitch.category)}} pitch</u></h3>
            <h3 class="card-title">{{pitch.title |capitalize}}</h3>
            <h4 class="card-text">{{pitch.description}}</h4>
            <a href="/pitch/{{pitch.id}}"><button class="btn-toolbar btn-warning">VIEW PITCH</button></a>
          </div>
        </div>
      </div>
    {%endfor%}
  </div>
  {% else %}
  <h3 class="text-center">No pitches to display!!</h3>
  {% endif %}
  {% if current_user.is_authenticated %}
  <a href="/pitch/new"><button class="btn-toolbar btn-info">CREATE A PITCH</button></a>
  {% endif %}
</div>
{% endblock %}

app/templates/navbar.html
<!DOCTYPE html>
<div class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"> PITCH</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
         <li><a href="/">HOME</a></li>
         <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            CATEGORIES
          </a>
          <div class="dropdown-menu bg-info" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="/pitches/interview">INTERVIEW</a><br>
            <a class="dropdown-item" href="/pitches/promotion">PROMOTION</a><br>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="/pitches/motivation">MOTIVATION</a><br>
            <a class="dropdown-item" href="/pitches/product">PRODUCT</a><br>
          </div>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if current_user.is_authenticated %}
        <li><a href="{{url_for('main.profile',uname=current_user.username)}}"><button class="btn-xs btn-warning">PROFILE</button></a></li>
        <li><a href="{{url_for('auth.logout')}}"><button class="btn-xs btn-warning">SIGN OUT</button></a></li>
        {% else %}
        <li><a href="{{url_for('auth.login')}}"><button class="btn-xs btn-danger">SIGN IN</button></a></li>
        {% endif %}
      </ul>
    </div> 
  </div>
 </div>   

app/templates/newpitch.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block styles%}
  {{ super() }}
  <link rel="stylesheet" href="{{url_for('static' , filename='css/index.css')}}">
{% endblock %}
{% block content %}
<div class="container">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title">Create a pitch</h3>
                <hr>
                {{ wtf.quick_form(pitch_form) }}
            </div>
        </div>
    </div>

</div>

{% endblock %}

app/templates/pitch.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block styles%}
  {{ super() }}
  <link rel="stylesheet" href="{{url_for('static' , filename='css/index.css')}}">
{% endblock %}
{%block content%}
<div class="container">
  <div class="card">
    <div class="card-body">
      <h3 class="card-title">{{pitch.title}}</h3>
        <p class="card-text">{{pitch.description}}</p>
        <hr>
        <p class="card-text">by {{pitch.user.username| capitalize}}</p>
        {% if current_user.is_authenticated %}
        <a href="/pitch/{{pitch.id}}?upvote=1">
          <button class="btn-xs btn-success">UPVOTE</button>
        </a><span class="fa-2x">{{pitch.upvotes}}</span>
        <a class="ml-3" href="/pitch/{{pitch.id}}?downvote=1">
          <button class="btn-xs btn-danger">DOWNVOTE</button>
        </a><span class="fa-2x">{{pitch.downvotes}}</span>
        <h4>Comments</h4>
          <hr>
          {{ wtf.quick_form(comment_form) }}
          
          {%for comment in comments%}
            <h4>{{comment.user.username}} : {{comment.content}}</h4>
          {%endfor%}
        {% endif %}  
    </div>
  </div>
</div>        
{%endblock%}

app/templates/profile/profile.html
{% extends 'base.html'%}
{% block styles%}
  {{ super() }}
  <link rel="stylesheet" href="{{url_for('static' , filename='css/index.css')}}">
{% endblock %}
{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-3">
    <h3><u>{{user.username| capitalize}}</u> </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  
  {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
  {% endif %}
  </div>
  <div class="col-md-4">
    {% if user.profile_pic_path %}

    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

    {%else%}
    <p>No profile picture</p>

    {% endif %}

        {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
    </form>
      {% endif %}
  </div>
  <div class="col-md-5">
    {%for pitch in pitches%}
    <div class="col-md-6 col-sm-6 mb-3 d-flex">
    <div class="card flex-fill">
        <div class="card-body">
            <h4><u>{{(pitch.category | capitalize)}}</u></h4>
            <h4 class="card-title"><u>{{pitch.title}}</u></h4>
            <p class="card-text">{{pitch.description}}</p>
            <a href="/pitch/{{pitch.id}}" class="btn btn-outline-info">View Pitch</a>
        </div>
    </div>
</div>
{%endfor%}
  </div>
 </div>
 </div> 
 {% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block styles%}
  {{ super() }}
  <link rel="stylesheet" href="{{url_for('static' , filename='css/index.css')}}">
{% endblock %}
{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}